reference:    "input/genome.fa"
input_dir:    "input"
output_dir:   "output"
n_chunks:     200
iteralign_params: "--read-len 150 --aligner bowtie2"

remote:
  bucket_name:  'smk-k8s-vapormap-bucket'
  cluster_name: 'smk-k8s-vapormap-cluster'
  cluster_size: 12
