#!/bin/bash
# Assuming google-cloud-sdk is installed and setup, and a project is set up
# Also assuming you have a file named test.txt inside your google storage  bucket
NODES=$1
CLUSTER_NAME=smk-k8s-vapormap-cluster

# 1: setup kubernetes cluster
gcloud container clusters create "$CLUSTER_NAME" --num-nodes="$NODES" --scopes storage-rw --zone europe-west1-d
gcloud container clusters get-credentials "$CLUSTER_NAME"

# 2: log into google storage
gcloud auth application-default login

