#!/bin/bash
# Assuming google-cloud-sdk is installed and setup, and a project is set up
# Also assuming you have a file named test.txt inside your google storage  bucket

NODES=$1
# Fetch cluster name in config file
CLUSTER_NAME=$(grep 'cluster_name *: *' config.yaml | tr -d " \"\'")
CLUSTER_NAME=${CLUSTER_NAME//*cluster_name:/}

if [ -z "$NODES" ]; then
  echo "You must specify the number of nodes to include in the cluster"
  exit 1
fi

if [ -z "$CLUSTER_NAME" ]; then
  echo "Error: cluster_name not defined in config.yaml"
  exit 1
fi

# 1: setup kubernetes cluster
gcloud container clusters create "$CLUSTER_NAME" \
        --machine-type n1-standard-4 \
        --num-nodes="$NODES" \
        --scopes storage-rw \
        --zone europe-west1-d
gcloud container clusters get-credentials --zone europe-west1-d "$CLUSTER_NAME"

# 2: log into google storage
gcloud auth application-default login

