#!/bin/bash

# Fetch cluster name in config file
BUCKET_NAME=$(grep 'bucket_name *: *' config.yaml | tr -d " \"\'")
BUCKET_NAME=${BUCKET_NAME//*bucket_name:/}

if [ -z ${BUCKET_NAME} ]; then
  echo "Error: bucket_name not defined in config.yaml"
  exit 1
fi
# Run snakemake through kubernetes and use data on the GS bucket
snakemake --default-remote-provider GS \
          --default-remote-prefix "$BUCKET_NAME" \
          --keep-remote \
          --use-singularity \
          --kubernetes
